
import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]

[env]
TERM = "xterm-256color"


[window]
padding.x = 10
padding.y = 10
dimensions.columns = 133
dimensions.lines = 40


decorations = 'Buttonless'

opacity = 0.8
blur = true

option_as_alt = "Both"

[font]
normal={family = "CaskaydiaMono Nerd Font Mono", style = "Regular"}
#normal={family = "Terminess Nerd Font Mono", style = "Regular"}
size = 16
